quartiq/miniconf

.github/workflows/ci.yml
Cargo.toml
derive_stringset/src/lib.rs
examples/example1.rs

This PR adds CI test support and closes #3

Adding CI support

---

.gitignore
derive_stringset/src/lib.rs
examples/example1.rs
src/lib.rs
tests/arrays.rs

Implement support for setting specific array indices

---

derive_stringset/src/lib.rs
examples/example1.rs
tests/enums.rs

Closes #6 
Only supports simple enums.

Added support for enums

---

.github/workflows/ci.yml
Cargo.toml

This PR adds in a `cargo-audit` CI check and also fixes the vulnerable heapless version.

Addressing generic_array vulnerability

---

Cargo.toml
LICENSE-MIT
derive_miniconf/Cargo.toml

This PR fixes #23 by adding an MIT license to the repository.

Adding MIT licensing

---

py/miniconf-mqtt/README.md

Small pr to update the command for installation in the readme of py/miniconf-mqtt

---

derive_miniconf/src/lib.rs
src/array.rs
src/lib.rs
src/option.rs
tests/arrays.rs

symmetric error

---

CHANGELOG.md
Cargo.toml
py/miniconf-mqtt/miniconf/__main__.py
py/miniconf-mqtt/miniconf/miniconf.py

This PR bumps the minimq version and fixes an issue with the user property serialization ordering.

Fixing user property ordering

---

CHANGELOG.md
Cargo.toml

v0.7.1 prep

---

README.md
miniconf_derive/src/lib.rs
src/array.rs
src/lib.rs
src/mqtt_client/mod.rs
src/option.rs
tests/integration_test.rs

preserve serde error info

---

CHANGELOG.md
README.md
examples/mqtt.rs
examples/readback.rs
miniconf_derive/src/lib.rs
src/array.rs
src/iter.rs
src/lib.rs
src/mqtt_client/mod.rs
src/option.rs
tests/arrays.rs
tests/integration_test.rs
tests/iter.rs
tests/option.rs
tests/structs.rs
tests/validation_failure.rs

- fix option depth
- exact depth
close #169

depth exact

---

py/miniconf-mqtt/miniconf/miniconf.py

- fix path start
- also enforce set() paths to start with /
- fixed `--list`

py path fix

---

CHANGELOG.md
Cargo.toml
miniconf_derive/src/lib.rs
src/array.rs
src/json_core.rs
src/mqtt_client.rs
src/option.rs
src/tree.rs
tests/structs.rs

- pull in serde/std with std
- support borrowed deserialize

deserialize borrowed

---

miniconf_derive/src/lib.rs

field names are 'static

---

CHANGELOG.md
Cargo.toml
examples/mqtt.rs
py/miniconf-mqtt/miniconf/miniconf.py
src/lib.rs
src/mqtt_client.rs
tests/integration_test.rs
tests/republish.rs
tests/validation_failure.rs

Follow-on to https://github.com/quartiq/minimq/pull/144
This PR updates the MQTT client to the latest version of Minimq.

Refactoring MQTT client for latest Minimq

---

CHANGELOG.md
Cargo.toml
miniconf_derive/Cargo.toml

bump std-embedded-nal v0.2, other deps, release 0.9.0

---

src/lib.rs
tests/skipped.rs

I forgot to check in these unit tests alongside https://github.com/quartiq/miniconf/pull/183. Also fixed a clippy lint.

Adding unit tests for skipped attributes

---

Cargo.toml
py/miniconf-mqtt/miniconf/discover.py
src/mqtt_client.rs

- make serde derive optional
- heapless 0.8

deps, heapless 0.8

---

CHANGELOG.md
examples/mqtt.rs
src/mqtt_client.rs
tests/integration_test.rs
tests/republish.rs
tests/validation_failure.rs

in support and exploration of
https://github.com/quartiq/stabilizer/pull/862

mqtt: do not own settings

---

CHANGELOG.md
Cargo.toml
miniconf/Cargo.toml
miniconf_derive/Cargo.toml
miniconf_mqtt/Cargo.toml
py/miniconf-mqtt/miniconf/version.py

- v0.10.0 release chores
- miniconf-mqtt: dev bump env_logger
- update release date
- release order

release v0.10

---

.github/workflows/ci.yml

This PR updates CI to address deprecation notices and false-positives.

Updating CI workflow

---

CHANGELOG.md
miniconf/src/tree.rs
miniconf_mqtt/examples/mqtt.rs
miniconf_mqtt/src/lib.rs
py/miniconf-mqtt/miniconf/__main__.py
py/miniconf-mqtt/miniconf/discover.py
py/test.sh

- **TreeKey: fix docs on traverse/node, doctest updates**
- **mqtt: support alive info**
- **make alive configurable late**

alive payload

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf_cli/Cargo.toml
miniconf_derive/Cargo.toml
miniconf_mqtt/Cargo.toml
miniconf_mqtt/src/lib.rs
py/miniconf-mqtt/pyproject.toml

- **v0.13.0 chores**
- **remove debug**
- **chore: Release**

release v0.13.0

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf_derive/Cargo.toml
miniconf_mqtt/Cargo.toml
py/miniconf-mqtt/pyproject.toml

- **scpi: refine**
- **v0.16.0 chores**

release 0.16

---

miniconf/README.md
miniconf/examples/cli.rs
miniconf/examples/menu.rs
miniconf/examples/scpi.rs
miniconf/src/json.rs
miniconf/src/node.rs
miniconf/src/tree.rs
miniconf/tests/arrays.rs
miniconf/tests/basic.rs
miniconf_mqtt/src/lib.rs

- **trait usability improvements**
- **doc test formatting, style [nfc]**

trait usability

---

miniconf/Cargo.toml
miniconf/README.md
miniconf/examples/common.rs
miniconf/examples/menu.rs
miniconf/src/error.rs
miniconf/src/iter.rs
miniconf/src/key.rs
miniconf/src/leaf.rs
miniconf/src/tree.rs
miniconf/tests/arrays.rs
miniconf/tests/basic.rs
miniconf/tests/enum.rs
miniconf/tests/packed.rs
miniconf/tests/validate.rs
miniconf_mqtt/src/lib.rs

- **tests: add tuple integration test**
- **expand readme example**
- **use thiserror 2**
- **readme, docs, intokeys for keysiter**
- **style, collect**

thiserror, dependencies, style

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf/src/lib.rs

- **release v0.17.1**
- **docs for no features**

release 0.17.1

---

miniconf/tests/common/mod.rs
py/miniconf-mqtt/pyproject.toml

- **tests: parasitic Packed sorted test**
- **py: fix license**

packed sorted

---

miniconf/src/key.rs

in no-deps downstream builds
https://github.com/quartiq/idsp/actions/runs/13237385624/job/36945017175

keys: remove potentially broken doc link

---

py/miniconf-mqtt/miniconf/async_.py
py/miniconf-mqtt/miniconf/sync.py

py: print values as repr

---

miniconf_mqtt/examples/mqtt.rs
py/miniconf-mqtt/miniconf/__init__.py
py/miniconf-mqtt/miniconf/__main__.py
py/miniconf-mqtt/miniconf/async_.py
py/miniconf-mqtt/miniconf/common.py
py/miniconf-mqtt/miniconf/sync.py
py/test.sh

also make the example mqtt client use unit for exit request event

py: introduce common for async/sync commonalities

---

CHANGELOG.md
miniconf/README.md
miniconf/examples/trace.rs
miniconf/src/error.rs
miniconf/src/leaf.rs
miniconf/src/tree.rs
miniconf/src/walk.rs
miniconf/tests/enum.rs
miniconf/tests/validate.rs
miniconf_derive/src/field.rs
miniconf_mqtt/examples/mqtt.rs
py/test.sh

- **tests: add enum tag test without StrLeaf**
- **README: add trace mention**
- **Walk: document better**
- **get/get_mut/validate -> with(...)**
- **remove Traversal::Invalid**

impl overrides
