quartiq/miniconf

README.md

This PR adds an initial README to the repository. We should echo a lot of this documentation into the rustdocs later as well.

Adding initial README documentation

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
src/mqtt_interface.rs
tests/integration_test.rs

This PR adds an MQTT-based settings interface and closes #5.
There is also an integration test added that can run if a broker (e.g. mosquitto) is running on the local machine.

Adding MQTT-based interface

---

derive_stringset/src/lib.rs

This PR fixes #19 by updating the derive macro to ue the fully-specified miniconf::StringSet trait path. This ensures that generated code can always find the `StringSet` trait even when it isn't directly imported into the current scope.

Updating derive trait path

---

src/lib.rs
tests/arrays.rs

This PR fixes #21 by checking if there is remaining topic data for array elements before recursing into `string_set()`.

Fixing configuring terminal array elements

---

src/mqtt_interface.rs

This PR fixes #33 by updating the error handlers to replace the `client` into the internal option whenever an error occurs.
Alternative approach would be to keep internal state within `RefCell`s

Updating state management to keep client in error conditions

---

src/mqtt_interface.rs

This behaviour is suggested in a (non-normative) comment in the MQTT 5.0
spec, and allows requesters to keep track of multiple in-flight operations.

Attach any request correlation data to responses

---

Cargo.toml

This PR updates the dependencies to remote old features and dependencies that are no longer used. It also updates `serde-json-core` to 0.3.0 to utilize safer heapless versions.

Updating dependencies

---

derive_miniconf/src/lib.rs
src/lib.rs

This PR adds documentation for each error code.
This will allow stabilizer docs to defer to cargo-doc output for error codes returned via the miniconf run-time settings interface.

Adding docs for errors

---

Cargo.toml

This PR locks down the `std-embedded-nal` revision, so we aren't dependent on a moving target. This was my fault originally - we should never track branches as dependencies without a lock file.

Locking down dev dependency revision

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
derive_miniconf/Cargo.toml
derive_miniconf/src/lib.rs
examples/mqtt.rs
src/lib.rs
src/mqtt_client/mqtt_client.rs
tests/integration_test.rs

This PR cleans up Miniconf for initial release. It also does the following:
* Add support for using const-generics to implement `Miniconf` for array types
* Added an async example for running Miniconf on-host
* Revamps docs to include more helpful information

Preparing library for release

---

derive_miniconf/src/lib.rs
src/lib.rs
tests/generics.rs

This PR fixes #56 by removing unnecessary trait bounds on the generic implementation for array types.
This PR also refactors the Miniconf trait implementation in the proc macro to include a where-clause for implementing `Miniconf` and `DeserializeOwned` for any generic type parameters on the struct.
For any `MiniconfAtomic` or Enum types, the additional bound of `Self: DeserializeOwned` is also added to ensure deserialization into `self` is possible.

Fixing trait bounds on miniconf array implementations

---

Cargo.toml
examples/mqtt.rs
py/miniconf-mqtt/miniconf/__init__.py
py/miniconf-mqtt/miniconf/__main__.py
src/mqtt_client/mqtt_client.rs
tests/integration_test.rs

This PR integrates a `prefix/connected` topic which contains the retained connected state of the client. A `Will` is set up such that this topic will be written with the value "0" when disconnected and "1" is written when the device is connected.
Additionally, the python utilities have been modified such that query of existing devices can be completed. If no `prefix` is provided, a prefix will automatically be identified using the newly exposed connection state.
TODO:

Report connection state via topic, expose automatic prefix detection

---

CHANGELOG.md
py/miniconf-mqtt/miniconf/__main__.py

This PR fixes some unintended CLI changes introduced in #61.
This PR also updates the CHANGELOG to mention the new `alive` topic.

Reverting python API, adding CHANGELOG

---

CHANGELOG.md
derive_miniconf/src/lib.rs
examples/readback.rs
src/iter.rs
src/lib.rs
tests/arrays.rs
tests/enums.rs
tests/generics.rs
tests/iter.rs
tests/structs.rs

This PR does the following:
* Exposes a `string_get()` API
* Refactors `recursive_iter()` to just iterate across the possible topic names (keys)
* Adds in an `iter` module that contains all iteration-related code.
* Merges `develop`
* Adds a `get_metadata()` API to determine maximum necessary topic + state buffer sizes

Refactoring readback support

---

CHANGELOG.md
examples/mqtt.rs
src/mqtt_client/mqtt_client.rs
tests/integration_test.rs
tests/republish.rs

This PR fixes #74 by updating the MqttClient to accept the initial settings to allow the user to provide some non-default values.

Updating MqttClient to accept initial settings values

---

CHANGELOG.md
src/array.rs
src/lib.rs
src/option.rs
tests/option.rs

This PR adds support for using `Option` with Miniconf. An `Option` is used to indicate a the presence of a setting at run-time. If a portion of the settings tree is set to None, it cannot be configured and will not be iterated over as a path string.
If the setting is Some, the option is transparent to Miniconf and struct will act as if the Option does not exist at all.
I've also moved the `array` implementation to a separate file to clean things up a bit.
This PR fixes #76 
TODO:

Adding support for Options

---

CHANGELOG.md
Cargo.toml
README.md
derive_miniconf/Cargo.toml
src/lib.rs

I've cleaned up the README here to point to the docs.rs page to intentionally ensure that all of the code examples are tested via Cargo. I also expanded and reformatted some of the library documentation in preparation for 0.4.0's release.

Preparing for miniconf release 0.4.0

---

CHANGELOG.md
examples/readback.rs
src/lib.rs
src/mqtt_client/mod.rs
tests/iter.rs
tests/option.rs

This PR fixes #87 by renaming the `iter()` methods to `iter_settings()` to avoid conflicting with the resolution lookup ordering of `core::slice::iter()`

Renaming iterator functions to prevent name conflicts

---

CHANGELOG.md
Cargo.toml
derive_miniconf/Cargo.toml

This PR fixes #86 by fixing the repo link for `derive_miniconf` and prepares for a 0.5 release.

Staging 0.5.0 miniconf release

---

CHANGELOG.md
py/miniconf-mqtt/miniconf/__main__.py
py/miniconf-mqtt/miniconf/miniconf.py

This PR fixes #94 by updating the python client to store UUID as the correlation data and use a static response topic.
This PR fixes #84 by updating the python API to be no-retain by default.
This PR fixes #57 by adding a timeout to the Python API.

Cleaning up python client

---

CHANGELOG.md
derive_miniconf/src/lib.rs
examples/readback.rs
src/array.rs
src/iter.rs
src/lib.rs
src/mqtt_client/mod.rs
src/option.rs
tests/arrays.rs
tests/enums.rs
tests/generics.rs
tests/iter.rs
tests/option.rs
tests/structs.rs

* a small step towards #104
* Changes the path assembly logic to postfix the separator. This is a bit easier in the logic.
* makes `metadata()` an associated fn
* homogenizes the API and e.g. makes the mqtt client and the unittests use `set()` where appropriate
* also makes the metadata semantically correct (depth N if there are N elements in the path)
* make `next_path` and related API associated fns
* Move the iterator state into the iterator
* fixes #88 by iterating all paths regardless of `Option` nulls.
* adds `Error::PathAbsent` to mark runtime absence in the case of `Option::None`.

rework (make get/set_path generic Peekable, associated fns for metadata and next_path)

---

README.md
derive_miniconf/src/field.rs
derive_miniconf/src/lib.rs
src/array.rs
src/option.rs
tests/arrays.rs
tests/structs.rs

* refactor the derive macro a bit, move out the arms into functions, remove `TypeDefinition`, cancel some common code
* derive common traits for Array and Option
* support zero length arrays and structs

reorganize derive macro

---

CHANGELOG.md
src/array.rs
src/option.rs

* enables/eases repr()-setting of containing structs
* enforces same layout as inner
* not breaking

repr(transparent) for option and array

---

CHANGELOG.md
Cargo.toml

This PR releases miniconf as 0.7
I'll follow up with a python release to pip as well following this now that things have stabilized a bit.

Bumping client, releasing Miniconf

---

CHANGELOG.md
src/mqtt_client/mod.rs

only reply if response topic set

---

CHANGELOG.md
Cargo.toml
README.md
examples/readback.rs
miniconf_derive/src/lib.rs
src/array.rs
src/iter.rs
src/lib.rs
src/mqtt_client/mod.rs
src/option.rs
tests/arrays.rs
tests/enums.rs
tests/generics.rs
tests/iter.rs
tests/option.rs
tests/structs.rs

Close #104 
Close #103 
Tested in `fls` where it also makes the code 1.2 kB smaller.
Downside is that we loose serde error source information.

be generic over serde mechanism and path hierarchy separator

---

CHANGELOG.md
README.md
examples/readback.rs
src/iter.rs
src/lib.rs
src/mqtt_client/mod.rs
tests/arrays.rs
tests/iter.rs
tests/option.rs
tests/structs.rs

The downside is that we don't check capacity anymore.
For most things that are `Write` they don't have a capacity.
On the other hand this was always done redundantly also in the mqtt client.

be generic about the thing to write the path into

---

CHANGELOG.md
README.md
examples/mqtt.rs
examples/readback.rs
miniconf_derive/src/field.rs
miniconf_derive/src/lib.rs
src/array.rs
src/iter.rs
src/json_core.rs
src/lib.rs
src/mqtt_client/mod.rs
src/option.rs
tests/arrays.rs
tests/basic.rs
tests/index.rs
tests/integration_test.rs
tests/iter.rs
tests/option.rs
tests/structs.rs
tests/validation_failure.rs

Removes the need for newtypes
Makes the iterator automatically know the required state size

make miniconf trait generic over depth

---

miniconf_derive/src/lib.rs
src/array.rs
src/iter.rs
src/json_core.rs
src/lib.rs
src/option.rs

- also iter: TooShort is unreachable
- {serialize,deserialize}_by_key

`serialize/deserialize_by_key`

---

README.md
miniconf_derive/src/field.rs
miniconf_derive/src/lib.rs
src/iter.rs
src/json_core.rs
src/lib.rs
src/option.rs
tests/generics.rs
tests/option.rs
tests/republish.rs

- update the generic bound logic in the derive macro
This rewrites the type bound logic after having analyzed it again and
after the changes due to adding the cont generic in `Miniconf`.
The Miniconf<Y> const generic Y is now the miniconf recursion depth
again. And it's an upper bound to the state size.
Before, the idea of making it exactly the key length war broken:
We had `impl Miniconf<0> for Option<T> where T: SerDe`
but for `#[miniconf(defer(1))] a: [Option<T>; N]` it would not use the
miniconf API of `Option<T>` as desired as it would for
`#[miniconf(defer(0))] a: Option<T>`.
Using the recursion depth as indicator which API to call fixes this.
At the cost of the state size now being potentially a bit too large.

recursion depth

---

CHANGELOG.md
Cargo.toml
examples/mqtt.rs
src/mqtt_client.rs
src/tree.rs
tests/republish.rs

This PR refactors how we handle responses to simplify the code base. Now, the function signature of the handler function just needs to `impl Debug` so we can format it into the response message on error.
Responses are now formatted directly into the MQTT payload. As such, there's no longer a limitation on maximum error sizes on the end-user, their limit is now restricted by how much buffer they provide for MQTT.

Reworking response handling

---

CHANGELOG.md
README.md
miniconf_derive/src/field.rs
src/array.rs
src/tree.rs

Adds support for skipping fields in a miniconf tree.
Fixes #182

Adding support for a `tree(skip)` field attribute

---

miniconf_mqtt/Cargo.toml
miniconf_mqtt/src/lib.rs
py/test.sh

- **mqtt: fix publish logic/error path, test alive, doctest**
- **remove unnecessary code**
- **bump env_logger**

mqtt rs rework

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf/src/array.rs
miniconf/src/json_core.rs
miniconf/src/key.rs
miniconf/src/tree.rs
miniconf_cli/Cargo.toml
miniconf_cli/src/lib.rs
miniconf_derive/src/lib.rs
miniconf_mqtt/Cargo.toml

- **make KeyLookup::NAMES an implementation detail**
- **bump deps**

remove KeyLookup::NAMES and apply dependencies update

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf/README.md
miniconf/examples/scpi.rs
miniconf/src/array.rs
miniconf/src/iter.rs
miniconf/src/json.rs
miniconf/src/jsonpath.rs
miniconf/src/key.rs
miniconf/src/lib.rs
miniconf/src/node.rs
miniconf/src/option.rs
miniconf/src/packed.rs
miniconf/src/tree.rs
miniconf/src/walk.rs
miniconf/tests/arrays.rs
miniconf/tests/basic.rs
miniconf/tests/generics.rs
miniconf/tests/packed.rs
miniconf/tests/skipped.rs
miniconf/tests/structs.rs
miniconf_derive/src/field.rs
miniconf_derive/src/tree.rs
miniconf_mqtt/src/lib.rs

- **force and use FusedIterator for KeysIter**
- **name_to_index -> NAMES**
- **[wip] add walk**
- **[wip] remove old metadata impls**
- **[wip] rename metadata -> path_metadata**
- **port to walk and remove path_metadata**
- **basic SCPI example**
- **change KeyLookup from trait to struct**
- **style, add a debug check**
- **change Walk::merge() args order**
- **example/scpi: expand**
- **walk: make fallible, use builder pattern**
- **Walk: inner -> internal**
- **walk() -> traverse_all()**

`KeyLookup` trait -> struct, `metadata()` -> `traverse_all::<W: Walk>()`

---

miniconf/README.md
miniconf/examples/common.rs
py/miniconf-mqtt/pyproject.toml

- **README/common: expand example with enum**
- **py: relax dependencies**

enum example, py deps

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf/src/error.rs
miniconf/src/impls.rs
miniconf/src/iter.rs
miniconf/src/json.rs
miniconf/src/jsonpath.rs
miniconf/src/key.rs
miniconf/src/leaf.rs
miniconf/src/node.rs
miniconf/src/packed.rs
miniconf/src/postcard.rs
miniconf/src/tree.rs
miniconf/src/walk.rs
miniconf_derive/Cargo.toml
miniconf_mqtt/Cargo.toml
miniconf_mqtt/src/lib.rs
py/miniconf-mqtt/miniconf/__main__.py
py/miniconf-mqtt/miniconf/discover.py
py/miniconf-mqtt/miniconf/miniconf.py
py/miniconf-mqtt/pyproject.toml

- **docs, inline, py client error handling**
- **v0.17.0 bumps**

releace 0.17.0

---

CHANGELOG.md
miniconf/Cargo.toml
miniconf/src/iter.rs
miniconf_derive/Cargo.toml
py/miniconf-mqtt/pyproject.toml

- **iter: add current_depth and root_depth**
- **v0.17.2 chores**

release v0.17.2
